### ISSUE TITLE
check for node.exe architecture  32/64 bit during build process

### ISSUE THREAD

**Issue by prashanthmadi** [christopheranderson/azure-demeteorizer#11]
I have successfully deployed my web app to azure but had below error message.

Error: `D:\home\site\wwwroot\programs\server\node_modules\fibers\bin\win32-ia32-v8-4.5\fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (D:\home\site\wwwroot\programs\server\node_modules\fibers\fibers.js:16:8)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\home\site\wwwroot\programs\server\boot.js:1:75)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

Solution : I was using 64bit version of node v0.10.40 in my local env. re-installing 32bit node v0.10.40 has fixed the issue
- It would be good if we can  add a check for node.js arch during build process.

``` javascript
  require('os').arch()
```

**Comment by prashanthmadi** [comment]
Customers can add 64-bit custom node.exe on their azure webapp using nodeProcessCommandLine in iisnode.yml file

-> I think providing an advisory info would be more appropriate than stopping their build process at precheck

**Comment by christopheranderson** [comment]
Most people ignore warning messages if they aren't blocking.

What if we block, with an error message pointing at docs for the version issue? Then users can use --ignore to bypass the error. Or, better yet, a specific --bypass-os-version flag.
