### ISSUE TITLE
Loading fibers npm module

### ISSUE THREAD

**Issue by ramijarrar** [christopheranderson/azure-demeteorizer#2]
I am not able to run the 'install' command successfully at the moment due to errors loading the fibers module. 

OS: Windows Server 2008
Node: 0.10.40 32 bit (as per the readme)

Pasted error:

``` shell
> fibers@1.0.5 install C:\Users\mathew-talos\Desktop\memex\application\src\.deme
teorized\bundle\programs\server\node_modules\fibers
> node ./build.js

C:\Users\mathew-talos\Desktop\memex\application\src\.demeteorized\bundle\program
s\server\node_modules\fibers>node "C:\Users\mathew-talos\AppData\Roaming\nvm\v0.
10.40\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gy
p.js" rebuild --release
gyp
npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\mathew-talos\Desktop\memex\application\src\.demeteorized\b
undle\programs\server
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
ERR! main Error encountered
ERR! main Error: npm install failed, see npm-debug.log for more details
ERR! main     at ChildProcess.<anonymous> (C:\Users\mathew-talos\AppData\Roaming
\nvm\v0.10.40\node_modules\azure-demeteorizer\lib\run-install.js:62:41)
ERR! main     at ChildProcess.emit (events.js:98:17)
ERR! main     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
ERR! main  [Error: npm install failed, see npm-debug.log for more details]
```

**Comment by ramijarrar** [comment]
Looking into this and it looks like the issue is that we need to have the VS command line tools installed to build fibers, I'll try again a little later and post back.

**Comment by christopheranderson** [comment]
Yes, this isn't going to be core to the way the tool works, but rather you should be able to debug the issue with `npm install fibers` and addressing the issues. In the end, you're going to need to install VS C++ redistributable. You also need to install Python 2.7. These are things I'd like to auto-detect for you before you install, though, so let me create a feature request for that.

**Comment by christopheranderson** [comment]
Closing this for now, due to the fact this isn't related to CLI tool. Checkout #3 to track the prechecks that will be added to the SDK. Feel free to add feedback there, or use this thread to debug this specific issue further. :)
