### ISSUE TITLE
Azure expects a different build of fibers

### ISSUE THREAD

**Issue by ramijarrar** [christopheranderson/azure-demeteorizer#4]
I was able to compile the fibers module and run my app locally without any errors, but when I deploy to Azure it fails to run due to an expectation of a different fibers build (namely win32-ia32-v8-4.5 ). I had a look through node_modules in the generated bundle and it appears what I have is "win32-ia32-v8-3.14".

Here is the full error on Azure:

``` shell
Error: `D:\home\site\wwwroot\programs\server\node_modules\fibers\bin\win32-ia32-v8-4.5\fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (D:\home\site\wwwroot\programs\server\node_modules\fibers\fibers.js:16:8)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\home\site\wwwroot\programs\server\boot.js:1:75)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

**Comment by christopheranderson** [comment]
Can you confirm your have the same version of node running locally and remotely? Preferably you can modify main.js to run `console.log(process.version)`. This looks like you might be using 0.10.32.

**Comment by ramijarrar** [comment]
I'm setting the version in the WEBSITE_NODE_DEFAULT setting that is created when I first deploy, is there somewhere else I need to set this?

EDIT: I checked again and it appears I was setting the value in the wrong App Service, thanks again for the help!

**Comment by christopheranderson** [comment]
Awesome. Thanks for trying the tool and giving some feedback!
